language: swift
osx_image: xcode11.3
git:
  depth: false
xcode_workspace: Workflow.xcworkspace
xcode_scheme: Workflow
xcode_destination: platform=iOS Simulator,name=iPhone 8
before_install:
  - brew cask install adoptopenjdk/openjdk/adoptopenjdk8
  - brew install jenv
  - export PATH="$HOME/.jenv/bin:$PATH"
  - eval "$(jenv init -)"
  - jenv add /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/
  - jenv global 1.8
  - java -version

install:
  - bundle install
script:
  - fastlane beta
addons:
  sonarcloud:
    organization: tyler-keith-thompson
    token:
      secure: "F2bnpQnc+7RH+jnA/8pdxZ697AzBrmlw+IJzLo51Mys+Uo5FnatGEqvSDfAMQQkXnGz6B/ngjiYFU1IBsmkbqFtENSi4eM4h+DTo76ayeYqQCyODd80Dg0pQI+4vjkhV1e1xJAvv3+lcLUtTFQarKAQdPtAUsXR8R6Xb5hZxAqfSS10QDohDcAPhi1+c2R5fZP9355+27Zs2O20LeGMTKjeUpRdhgbDcUiwt7rCXJyzYVE1iAG3pFrsW2gYdKt7DbPNK83j3UubZEBLzSY4ruQ/qi/vGFyDJ29a9L/jKhdgEcqdAvmzeRHXWqvFBEx5kfsJx3fo9GcjGA7cDk/yEsZRgEq28jGlCDaRCY9Zd984wDYLTLTUa0Qp2rhtXQB7jbiE2ZxXcgZrIW97RCRMTq4lcLouC/BdD3vcl7bZMZwb4Bxwtpr+apR67Hls/yBudRbZPBaWux6qBYT0BuW2CYg420CHA7jbSU7gVWGOZx761w8LsyvkWBktGQPHD+BfyPw++PHt+N9EgG0Qvk03c7xz7ed4NAj+4eewQc+DMzMItfucX0DzHzEUkGOLkvqwlnpO7lcDcucNPnmgcTCbmjKKBp8HNu9ygVpjojfEF/gz4pfFZ/NM/zthloOgqRDi3fcuYnuGr+ivq87G3Zuk7DmRX1tatQsICy0pv0aV5SjY="
script:
- fastlane unit_test
- ./xccov-to-sonarqube-generic.sh ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult > sq-generic.xml
- sonar-scanner
if: tag IS blank
deploy:
  provider: script
  script: ./deploy_pod.sh
  on:
    branch: master
env:
  global:
    secure: Tg+Nke1hzm/WJSFnVOmqAHK3yP89nIjtmdyDIHfvrahMKhaW8QOKFWN7dhTfBi6XKsCF5zIgZnGQQnGHKNf9hNQEiMRD7DX5UpIM54oGpozYhhf2gXa5SKsaHArQCQ1lpS+Q7qnGWSQt7fD0ME9ySaZiK45Xef5acNrD2Y5kk2o+4893/tkGi91X+ToZOJzUKcChciw27/KxGH2YDkQpQOwpAcR+F4NFILvEYKRj8/2VP26mZOdT3brGGMeSMptnduh2Ve8LXpYPSwrIBnGe+aC1XFP+f2xfJXZoKs7DnzE4FDqZC3oDVR+KgQFsRtBKIalScm0pnEWPdbXp0A0+fD25OkrbbQ+pOnK/bJIOrQ93xeXdADb1mbXkdxWjqErAg6kr9eB5DfTg9+lmN+vDwUvkH2MH38yb45moA30lau/YaPohSkuriuCI9OPo6BUa/o37PQGjabG9l1LNo2bEGNYJUq7rJfFsOF30tsow8jvcnh3k5WE45UWzuuSKdSigLuvxAL5RyysfbynHyD6TBZncETfx8q59XFE8H3cJC1DWqr58hvVMmsDKePyW1Hyo1e04i+SukUecF9fZMbunGd80oThgxv4+XubjRyZew++3z6RdRx8+droyeiFU9G5oeUynICnO18y0kaKd3Bi5MWkT2TglvH844/Wp/e0Qdaw=
1199f58eb2062eff33c4058f298c92926d4eb8ac:
  secure: XsMfRnfVDd8JeL+9AeuHbITxNYgf64o5wcsruEamjgAEOcjdt4BFTcguIYHd8QoQW7FLgGlC2O8G06BW4zhP7GJyAJPFeCHP0Rh0tMUyDcQbwmSI5FnNXYHxlVU+htM/0RImI+A4D5vZyns2XPF5WUMjxULduxD8Xw5TmLvXoN1WViHevBaPOjc8gPFuCuGg/XR5XYNx6tt2qTpw/wZes4L/oFn+vySpMM2CxjqZHDSmWsk3lzflZniQhrxjDpzZHoNh57HZnXpee29gqkaO9pgUh+7WcZMXNFRlZaCHj3uJUARTvsBkLaCvq07PjT+Kh2mbyMTOyDM2p2yynNd3YoAxrfGR5A5yN2dj/+drKuiUI0SwvRfQQfW1dVHB3tXYXhFr7QSKQWWvoq5Wj830gm75myVjwfqxxxGy257u0uNBrwnjcHr6qPaOqodd8oIwWkXfC+ifkohy3E+iLrGOZaZux15yzH71KA14rgIYYravofkRRWHVLuURSsA3Eoa/NpseLqRJA6XKHYQUSzY/4HsOLip9ucYIadjtbvH9Q8W2gMOGAkGcLdsPFGl/1RKqjuIjz5xfp3xyPt531GIHgIWQTpekTGhIH2ySUxYYvnzUDIiQe8cNxJGU92OCUR12S79kdN1AF3zhfatxVuagl7r06UTKKlH0sLo4ldkwhSs=
